import { Product } from "~~/interfaces/product"

export const products: Array<Product> = [
  {
    id: "sdfgdfgssd",
    title: "🎁100 ГЕМОВ в Brawl Stars🎁",
    price: 200,
    rate: 4.5,
    newprice: 100,
    type: "Наборы",
    subtype: "Особая акция",
    img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
    owner: {
      img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
      name: "Lisana",
      reviews: [],
      rate: 4.5,
      id: "lisanaasd",
    },
    description:
      "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
    reviews: [
      {
        id: "2387523578",
        rate: 2,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 2,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 1,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 3,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 3,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 1,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 5,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 5,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
    ],
    similar: [
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 2.1,
        newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 3.1,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 4.4,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 5,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
    ],
    tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
  },
  {
    id: "rftghjrthg",
    title: "🎁200 ГЕМОВ в Brawl Stars🎁",
    price: 150,
    rate: 4.5,
    newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
    img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
    owner: {
      img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
      name: "Lisana",
      reviews: [],
      rate: 4.5,
      id: "lisanaasd",
    },
    description:
      "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
    reviews: [
      {
        id: "2387523578",
        rate: 2,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 2,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 1,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 3,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 3,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 1,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 5,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 5,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
    ],
    similar: [
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 2.1,
        newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 3.1,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 4.4,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 5,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
    ],
    tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
  },
  {
    id: "rftgjths",
    title: "🎁300 ГЕМОВ в Brawl Stars🎁",
    price: 150,
    rate: 4.5,
    newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
    img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
    owner: {
      img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
      name: "Lisana",
      reviews: [],
      rate: 4.5,
      id: "lisanaasd",
    },
    description:
      "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
    reviews: [
      {
        id: "2387523578",
        rate: 2,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 2,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 1,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 3,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 3,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 1,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 5,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 5,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
    ],
    similar: [
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 2.1,
        newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 3.1,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 4.4,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 5,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
    ],
    tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
  },
  {
    id: "btrgrtwhyrtw",
    title: "🎁400 ГЕМОВ в Brawl Stars🎁",
    price: 150,
    rate: 4.5,
    newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
    img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
    owner: {
      img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
      name: "Lisana",
      reviews: [],
      rate: 4.5,
      id: "lisanaasd",
    },
    description:
      "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
    reviews: [
      {
        id: "2387523578",
        rate: 2,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 2,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 1,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 3,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 3,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 1,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 5,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 5,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
    ],
    similar: [
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 2.1,
        newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 3.1,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 4.4,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 5,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
    ],
    tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
  },
  {
    id: "sgffgdfgddgfdfgs",
    title: "🎁500 ГЕМОВ в Brawl Stars🎁",
    price: 150,
    rate: 4.5,
    newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
    img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
    owner: {
      img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
      name: "Lisana",
      reviews: [],
      rate: 4.5,
      id: "lisanaasd",
    },
    description:
      "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
    reviews: [
      {
        id: "2387523578",
        rate: 2,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 2,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 1,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 3,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 3,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 1,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 5,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 5,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
    ],
    similar: [
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 2.1,
        newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 3.1,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 4.4,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 5,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
    ],
    tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
  },
  {
    id: "sasdfasdfsh",
    title: "🎁600 ГЕМОВ в Brawl Stars🎁",
    price: 150,
    rate: 4.5,
    newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
    img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
    owner: {
      img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
      name: "Lisana",
      reviews: [],
      rate: 4.5,
      id: "lisanaasd",
    },
    description:
      "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
    reviews: [
      {
        id: "2387523578",
        rate: 2,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 2,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 1,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 3,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 3,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 1,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
      {
        id: "2387523578",
        rate: 5,
        value: "Zaebis nahui blyat",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 5,
          id: "lisanaasd",
        },
        parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
      },
    ],
    similar: [
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 2.1,
        newprice: 0,
    type: "Наборы",
    subtype: "Особая акция",
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 3.1,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 4.4,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
      {
        id: "ssfgjshgfsh",
        title: "🎁100 ГЕМОВ в Brawl Stars🎁",
        price: 150,
        rate: 5,
    type: "Наборы",
    subtype: "Особая акция",
        newprice: 0,
        img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
        owner: {
          img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
          name: "Lisana",
          reviews: [],
          rate: 4.5,
          id: "lisanaasd",
        },
        description:
          "Внимание! Если вы брали данное количество гемов(500) у другого продавца или у меня вам придет меньше гемов! Возврата в таком случае нет. После оплаты просьба предоставить почту от вашего аккаунта и ждать ответа",
        reviews: [
          {
            id: "2387523578",
            rate: 4,
            value: "Zaebis nahui blyat",
            owner: {
              img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
              name: "Lisana",
              reviews: [],
              rate: 4.5,
              id: "lisanaasd",
            },
            parentItemTitle: "🎁100 ГЕМОВ в Brawl Stars🎁",
          },
        ],
        similar: [],
        tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
      },
    ],
    tags: ["60 GOLD CUBES", "БЕЗ ВХОДА", "ЧЕРЕЗ ID", "ВЫПОЛНЯЮ ЗА 5 МИНУТ"],
  }
]